# Generated by Django 5.1.7 on 2025-03-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quote',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
