# Generated by Django 5.1.7 on 2025-03-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_rating_quote_shares_quote_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='theme',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
